name             'osdc-2015-demo'
maintainer       'Graylog, Inc.'
maintainer_email 'bernd@graylog.com'
license          'Apache2'
description      'Installs/Configures osdc-2015-demo'
long_description 'Installs/Configures osdc-2015-demo'
version          '0.1.0'

depends 'timezone_lwrp', '~> 0.1.6'
depends 'java', '~> 1.31.0'
depends 'mongodb', '~> 0.16.2'
depends 'elasticsearch', '~> 0.3.13'
depends 'graylog2', '1.0.3'
depends 'icinga2', '~> 2.1.8'
depends 'apache2', '~> 3.0.1'
depends 'mysql', '~> 6.0.21'
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'database', '~> 4.0.5'
depends 'rsyslog', '~> 1.15.0'
depends 'chef-client', '~> 4.3.0'
