name             'webapp'
maintainer       'Graylog, Inc.'
maintainer_email 'bernd@graylog.com'
license          'Apache2'
description      'Installs/Configures webapp'
long_description 'Installs/Configures webapp'
version          '0.1.0'
